file(GLOB SRC "./*.cpp")
add_executable(coordinate ${SRC})
message(STATUS "coordinate: ${SRC}")
target_link_libraries(coordinate PUBLIC base GTest::gtest GTest::gtest_main glfw3)
target_include_directories(coordinate PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_compile_definitions(coordinate PRIVATE RES_DIR="${CMAKE_CURRENT_SOURCE_DIR}")